import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { injectRootComponent, removeRootComponent } from "../injector";
import { resolvePlugin } from "../registry";

const temporaryDirectories: string[] = [];

afterEach(() => {
  for (const directory of temporaryDirectories.splice(0)) {
    fs.rmSync(directory, { recursive: true, force: true });
  }
});

function fixture(): { root: string; appPath: string } {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "storm-root-component-"));
  temporaryDirectories.push(root);
  const appPath = path.join(root, "client/src/App.tsx");
  fs.mkdirSync(path.dirname(appPath), { recursive: true });
  fs.writeFileSync(appPath, `import { StormLayout } from "@stormstack/react";

export default function App() {
  return (
    <>
      <StormLayout appName="Test" />
      {/* storm:root-components */}
    </>
  );
}
`);
  return { root, appPath };
}

describe("root component injection", () => {
  it("adds and removes authenticated ConsentBanner idempotently", () => {
    const consent = resolvePlugin("consent");
    if (!consent) throw new Error("Consent plugin metadata missing");
    const { root, appPath } = fixture();

    expect(injectRootComponent(root, consent, "npm", "plugins").modified).toBe(true);
    expect(injectRootComponent(root, consent, "npm", "plugins").modified).toBe(false);
    let source = fs.readFileSync(appPath, "utf8");
    expect(source).toContain('import { ConsentBanner } from "@stormstack/consent/client"');
    expect(source).toContain('import { useStorm } from "@stormstack/react"');
    expect(source).toContain("const { user } = useStorm()");
    expect(source).toContain("return user ? <ConsentBanner /> : null");
    expect(source).toContain("<StormRootConsentBanner />");
    expect(source).toContain("storm:root-component @stormstack/consent:start");

    expect(removeRootComponent(root, consent).modified).toBe(true);
    expect(removeRootComponent(root, consent).modified).toBe(false);
    source = fs.readFileSync(appPath, "utf8");
    expect(source).not.toContain("ConsentBanner");
    expect(source).not.toContain("useStorm");
    expect(source).toContain("storm:root-components");
  });

  it("fails safely when the generated marker is absent", () => {
    const consent = resolvePlugin("consent");
    if (!consent) throw new Error("Consent plugin metadata missing");
    const { root, appPath } = fixture();
    fs.writeFileSync(appPath, "export default function App() { return null; }\n");

    expect(injectRootComponent(root, consent, "npm", "plugins")).toMatchObject({
      modified: false,
      reason: expect.stringContaining("manuellement"),
    });
  });

  it("removes a customized Consent block generated by create-storm-app", () => {
    const consent = resolvePlugin("consent");
    if (!consent) throw new Error("Consent plugin metadata missing");
    const { root, appPath } = fixture();
    fs.writeFileSync(appPath, `import { StormLayout, StormRouter } from "@stormstack/react";
import { useStorm } from "@stormstack/react"; // storm:root-auth-import @stormstack/consent
import { ConsentBanner } from "@stormstack/consent/client"; // storm:root-component-import @stormstack/consent

/* storm:root-auth @stormstack/consent:start */
function StormRootConsentBanner() {
  const { user } = useStorm();
  return user ? <ConsentBanner policyVersion="2026-08" /> : null;
}
/* storm:root-auth @stormstack/consent:end */

export default function App() {
  return (
    <>
      <StormLayout appName="Test"><StormRouter /></StormLayout>
      {/* storm:root-components */}
      {/* storm:root-component @stormstack/consent:start */}
      <StormRootConsentBanner />
      {/* storm:root-component @stormstack/consent:end */}
    </>
  );
}
`);

    expect(removeRootComponent(root, consent).modified).toBe(true);
    const source = fs.readFileSync(appPath, "utf8");
    expect(source).not.toContain("ConsentBanner");
    expect(source).not.toContain("useStorm");
    expect(source).toContain("StormLayout, StormRouter");
  });

  it("preserves a pre-existing useStorm binding and unrelated user logic", () => {
    const consent = resolvePlugin("consent");
    if (!consent) throw new Error("Consent plugin metadata missing");
    const { root, appPath } = fixture();
    fs.writeFileSync(appPath, `import { useStorm } from "@stormstack/react";

export default function App(): JSX.Element {
  const { user } = useStorm();
  console.log(user);
  return <>
      {/* storm:root-components */}
  </>;
}
`);

    expect(injectRootComponent(root, consent, "npm", "plugins").modified).toBe(true);
    expect(removeRootComponent(root, consent).modified).toBe(true);
    const source = fs.readFileSync(appPath, "utf8");
    expect(source).toContain('import { useStorm } from "@stormstack/react"');
    expect(source).toContain("const { user } = useStorm()");
    expect(source).toContain("console.log(user)");
    expect(source).not.toContain("ConsentBanner");
  });

  it("does not confuse aliased imports with the exact bindings used by the wrapper", () => {
    const consent = resolvePlugin("consent");
    if (!consent) throw new Error("Consent plugin metadata missing");
    const { root, appPath } = fixture();
    fs.writeFileSync(appPath, `import { StormLayout, useStorm as existingStormHook } from "@stormstack/react";
import { ConsentBanner as ExistingConsentBanner } from "@stormstack/consent/client";

void existingStormHook;
void ExistingConsentBanner;

export default function App() {
  return <>
      <StormLayout appName="Test" />
      {/* storm:root-components */}
  </>;
}
`);

    expect(injectRootComponent(root, consent, "npm", "plugins").modified).toBe(true);
    const source = fs.readFileSync(appPath, "utf8");
    expect(source).toContain('import { useStorm } from "@stormstack/react";');
    expect(source).toContain('import { ConsentBanner } from "@stormstack/consent/client";');
    expect(source).toContain("const { user } = useStorm()");
    expect(source).toContain("return user ? <ConsentBanner /> : null");
  });

  it("refuses injection without writing when useStorm is bound to another module", () => {
    const consent = resolvePlugin("consent");
    if (!consent) throw new Error("Consent plugin metadata missing");
    const { root, appPath } = fixture();
    const before = fs.readFileSync(appPath, "utf8").replace(
      'import { StormLayout } from "@stormstack/react";',
      'import { StormLayout } from "@stormstack/react";\nimport { useStorm } from "custom-hooks";',
    );
    fs.writeFileSync(appPath, before);

    expect(injectRootComponent(root, consent, "npm", "plugins")).toMatchObject({
      modified: false,
      reason: expect.stringContaining("useStorm"),
    });
    expect(fs.readFileSync(appPath, "utf8")).toBe(before);
  });

  it("refuses a partial removal when an owned end marker is missing", () => {
    const consent = resolvePlugin("consent");
    if (!consent) throw new Error("Consent plugin metadata missing");
    const { root, appPath } = fixture();
    expect(injectRootComponent(root, consent, "npm", "plugins").modified).toBe(true);
    const before = fs.readFileSync(appPath, "utf8").replace(
      "      {/* storm:root-component @stormstack/consent:end */}\n",
      "",
    );
    fs.writeFileSync(appPath, before);

    expect(removeRootComponent(root, consent)).toMatchObject({
      modified: false,
      blocked: true,
      reason: expect.stringContaining("incomplet"),
    });
    expect(fs.readFileSync(appPath, "utf8")).toBe(before);
  });

  it("blocks removal when only owned imports remain", () => {
    const consent = resolvePlugin("consent");
    if (!consent) throw new Error("Consent plugin metadata missing");
    const { root, appPath } = fixture();
    const before = fs.readFileSync(appPath, "utf8").replace(
      'import { StormLayout } from "@stormstack/react";',
      'import { StormLayout } from "@stormstack/react";\nimport { ConsentBanner } from "@stormstack/consent/client"; // storm:root-component-import @stormstack/consent',
    );
    fs.writeFileSync(appPath, before);

    expect(removeRootComponent(root, consent)).toMatchObject({
      modified: false,
      blocked: true,
      reason: expect.stringContaining("incomplet"),
    });
    expect(fs.readFileSync(appPath, "utf8")).toBe(before);
  });
});
